apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      endpoint: ocs-storagecluster-cephobjectstore-openshift-storage.apps.isar.coe.muc.redhat.com
      bucket: rhacm-thanos-bucket-4904c404-6de6-4731-bad1-8cc81ba81bbc
      insecure: true
      access_key: X83EPD5LOU393BOF9WMH
      secret_key: igGWX0oIk3PUhiE2QNKO3uBq43ycEkZsvH0GiV8h
