apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: rhacm-thanos-bucket-f1c91adf-3ff6-49b2-b63e-5f15e7d89d37
      endpoint: s3-openshift-storage.apps.ocp4.stormshift.coe.muc.redhat.com:80
      insecure: true
      access_key: AWaaVmjBvLYvAtXqSml2
      secret_key: +wp2QEjWlJYWxA6J4MxtVKqRnTs44lgOMr+/kQOK
