apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: rhacm-thanos-bucket-d240ea7f-82be-4fe2-9869-459b97cfefe6 
      endpoint: ceph-s3-openshift-storage.apps.ocp10.stormshift.coe.muc.redhat.com:80
      insecure: true
      access_key: IIVE5GWZ4F08JRDOMQ7A
      secret_key: jVwcLPhfvPFvcK3pw3vUyN8q6vhI0dhMTQMRKRIl 
