---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Enable Required Repos
      tags: repos,slow
      rhsm_repository:
        name:
          - rhel-7-server-rpms
          - rhel-8-for-x86_64-appstream-rpms
      become: true

    - name: Install required packages
      tags: packages,slow
      yum:
        name:
          - ansible
          - git
          - gcc
          - genisoimage
          - isomd5sum
          - nmap
          - bind-utils
          - nfs-utils
          - pykickstart
          - ovirt-ansible-roles
          - python-ovirt-engine-sdk4
          - "/usr/bin/virt-customize"
          - pki-tools
          - tmux
          - python-devel
          - python-pip
          - python-openstack
          - atomic-openshift-clients
        state: latest
      become: true

    - name: Updating all packages to latest
      tags: repos,slow
      yum:
        name: '*'
        state: latest
      become: true

    - name: Prepare for openshift ansible part1
      tags: openshift,ansible
      pip:
        name: setuptools
        extra_args: --upgrade

    - name: Prepare for openshift ansible part2
      tags: openshift,ansible
      pip:
        name: openshift, passlib, pyOpenSSL
        extra_args: --user

    - name: Install ansible roles
      tags: ansible, roles
      shell: ansible-galaxy install redhatinsights.insights-client

    - name: Install ansible roles
      tags: ansible, roles
      shell:  ansible-galaxy collection install ansible.posix community.general community.crypto

    - name: Add CA Certs for openshift ansible modules
      when: sysctx_certs_path is defined
      tags: openshift,ansible
      lineinfile:
          path: /root/.bashrc
          line: "export K8S_AUTH_SSL_CA_CERT={{sysctx_certs_path}}/redhat-pki-ca-chain.crt"

    - name: prepare pki
      tags: pki
      lineinfile:
        create: true
        line: "fjfj"
        path: "~/.pki.password"
        mode: "600"

    - name: init pki
      tags: pki
      command: "pki -C ~/.pki.password client-init"
      register: pki
      ignore_errors: true
      failed_when: "pki.rc!=0 and pki.stdout is not search('Security database already exis')"
      changed_when: pki.rc == 0

    - name: connect pki
      tags: pki
      command: "pki -v -C ~/.pki.password -U 'https://ca.corp.redhat.com:8443/ca' cert-show 0x1"

    - name: generate private key
      when: sysctx_certs_path is defined
      tags: cert
      openssl_privatekey:
        type: RSA
        size: 4096
        path: ~/stormshift.key

    - name: generate certifacte request
      when: sysctx_certs_path is defined
      tags: cert
      register: csr
      openssl_csr:
        path: ~/stormshift.csr
        privatekey_path: ~/stormshift.key
        key_usage: nonRepudiation,digitalSignature,keyEncipherment
        key_usage_critical: true
        basicConstraints: "CA:FALSE"
        common_name: "*.stormshift.coe.muc.redhat.com"
        organization_name: "Red Hat"
        organizational_unit_name: "SolutionArchitectsDach"
        subject_alt_name:
          - "DNS:rhev.stormshift.coe.muc.redhat.com"
          - "DNS:monitor.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.ocp1.stormshift.coe.muc.redhat.com"
          - "DNS:api.ocp1.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.ocp2.stormshift.coe.muc.redhat.com"
          - "DNS:api.ocp2.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.ocp3.stormshift.coe.muc.redhat.com"
          - "DNS:api.ocp3.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.ocp4.stormshift.coe.muc.redhat.com"
          - "DNS:api.ocp4.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.ocp5.stormshift.coe.muc.redhat.com"
          - "DNS:api.ocp5.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.ocp6.stormshift.coe.muc.redhat.com"
          - "DNS:api.ocp6.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.ocp7.stormshift.coe.muc.redhat.com"
          - "DNS:api.ocp7.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.ocp8.stormshift.coe.muc.redhat.com"
          - "DNS:api.ocp8.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.ocp9.stormshift.coe.muc.redhat.com"
          - "DNS:api.ocp9.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.ocp10.stormshift.coe.muc.redhat.com"
          - "DNS:api.ocp10.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.ocp11.stormshift.coe.muc.redhat.com"
          - "DNS:api.ocp11.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.ocp12.stormshift.coe.muc.redhat.com"
          - "DNS:api.ocp12.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.ocp13.stormshift.coe.muc.redhat.com"
          - "DNS:api.ocp13.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.ocp14.stormshift.coe.muc.redhat.com"
          - "DNS:api.ocp14.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.ocp15.stormshift.coe.muc.redhat.com"
          - "DNS:api.ocp15.stormshift.coe.muc.redhat.com"
          - "DNS:*.apps.mmgt.stormshift.coe.muc.redhat.com"
          - "DNS:api.mmgt.stormshift.coe.muc.redhat.com"
          - "DNS:storm2.coe.muc.redhat.com"
          - "DNS:*.storm2.coe.muc.redhat.com"
          - "DNS:storm3.coe.muc.redhat.com"
          - "DNS:*.storm3.coe.muc.redhat.com"
          - "DNS:storm4.coe.muc.redhat.com"
          - "DNS:*.storm4.coe.muc.redhat.com"
          - "DNS:storm5.coe.muc.redhat.com"
          - "DNS:*.storm5.coe.muc.redhat.com"
          - "DNS:storm6.coe.muc.redhat.com"
          - "DNS:*.storm6.coe.muc.redhat.com"
          - "DNS:ushift1.stormshift.coe.muc.redhat.com"
          - "DNS:ushift2.stormshift.coe.muc.redhat.com"
          - "DNS:ushift3.stormshift.coe.muc.redhat.com"
          - "DNS:ushift4.stormshift.coe.muc.redhat.com"
          - "DNS:ushift5.stormshift.coe.muc.redhat.com"
          - "DNS:ushift6.stormshift.coe.muc.redhat.com"
          - "DNS:ushift7.stormshift.coe.muc.redhat.com"
          - "DNS:ushift8.stormshift.coe.muc.redhat.com"
          - "DNS:ushift9.stormshift.coe.muc.redhat.com"
          - "DNS:ushift10.stormshift.coe.muc.redhat.com"
          - "DNS:ushift-imgbld.stormshift.coe.muc.redhat.com"
          - "DNS:stormshiftdeploy.coe.muc.redhat.com"

    - block:
      - name: Prepare request xml from template
        tags: cert
        template:
          src: templates/redhatIAM_caServerCertRequest.xml.j2
          dest: "~/redhatIAM_caServerCertRequest.xml"

      - name: Insert CSR into  request xml
        tags: cert
        blockinfile:
          path: ~/redhatIAM_caServerCertRequest.xml
          block: "{{ lookup('file', '~/stormshift.csr')}}"
          insertafter: "INSERT-PKCS10-CSR-HERE"
          marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"

      - name: Remove Begin and End Markers from CSR in XML
        tags: cert
        replace:
          path: ~/redhatIAM_caServerCertRequest.xml
          regexp: "^-----(BEGIN|END) CERTIFICATE REQUEST-----$\n"
          replace: ""

      - name: Submit CSR to Red Hat Internal CA
        tags: cert
        command: "XXXpki -U 'https://ca.corp.redhat.com/ca'  cert-request-submit ~/redhatIAM_caServerCertRequest.xml"
      when: csr is changed
