---
# This playbook destroys an ushift rpm VM on OCPVirt
# Example to run manually:
# ansible-playbook -e ushift_env=ushift10 210-ushift-rpm-destroy.yaml

- hosts: "cluster_{{ ushift_env }}"
  gather_facts: false
  tasks:
    - name: Destroy MicroShift
      import_role:
        name: ushift_rpm_on_kubevirt
        tasks_from: 200-destroy.yml
