---
- name: Pre-deploy cluster
  hosts: "localhost"
  connection: local
  gather_facts: false
  tasks:

    - name: Debug information
      ansible.builtin.debug:
        msg:
          - "Run aggainst {{inventory_hostname}}, vars:"
          - " - stormshift_cluster_action : {{ stormshift_cluster_action }}"
          - " - stormshift_cluster_name : {{ stormshift_cluster_name }}"
        verbosity: 1

    - name: "import playbook stormshift-cluster-{{ stormshift_cluster_action }}"
      ansible.builtin.import_playbook: "stormshift-cluster-{{ stormshift_cluster_action }}.yaml"

