---
- hosts: cluster
  connection: local
  gather_facts: false
  tasks:

    # - name: List clusters
    #   community.hashi_vault.vault_list:
    #     url: "{{ lookup('ansible.builtin.env', 'RH_VAULT_URL' ) }}"
    #     auth_method: approle
    #     role_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_ROLE_ID' ) }}"
    #     secret_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_SECRET_ID' ) }}"
    #     validate_certs: false
    #     # engine_mount_point: apps

    #     path: "apps/metadata/coe-lab/cluster-credential"
    #   register: clusters

    # - debug: var=clusters
    - name: Get Creds
      community.hashi_vault.vault_kv2_get:
        url: "{{ lookup('ansible.builtin.env', 'RH_VAULT_URL' ) }}"
        auth_method: approle
        role_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_ROLE_ID' ) }}"
        secret_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_SECRET_ID' ) }}"
        validate_certs: false
        engine_mount_point: apps
        path: "coe-lab/cluster-credential/stormshift-{{ inventory_hostname }}"
      register: cluster  

    - name: Export kubeconfig
      copy:
        content: "{{ cluster.secret.kubeconfig }}"
        dest: "kubeconfig-stormshift-{{ inventory_hostname }}"
  

