apiVersion: v1
kind: DeploymentConfig
metadata:
  name: untaint-mtu-too-small
spec:
  replicas: 2
  selector:
    app: untaint-mtu-too-small
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: untaint-mtu-too-small
      name: untaint-mtu-too-small
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: untaint-mtu-too-small
            topologyKey: kubernetes.io/hostname
      serviceAccountName: untainter
      containers:
      - args:
        - bash
        - -c
        - |
          set -euo pipefail
          IFS=$'\n\t'

          oc observe nodes --output=gotemplate \
              --argument='{{with .spec.taints}}{{range .}}{{if eq .key "network.openshift.io/mtu-too-small"}}#tainted{{end}}{{end}}{{end}}' | \
          while IFS=' ' read -r _ _ _ _ nodename arguments; do
            if [[ -z "${nodename:-}" || ! "${arguments:-}" =~ tainted ]]; then
              continue
            fi
            oc adm taint nodes $nodename network.openshift.io/mtu-too-small-
          done
        command:
        - /usr/bin/env
        image: " "
        imagePullPolicy: IfNotPresent
        name: untainter
        ports:
        resources:
          limits:
            cpu: "200m"
            memory: 250Mi
          requests:
            cpu: "200m"
            memory: 250Mi
  triggers:
  - type: ConfigChange 
  - imageChangeParams:
      automatic: true
      containerNames:
      - untainter
      from:
        kind: ImageStreamTag
        name: cli:latest
        namespace: openshift
    type: ImageChange  
  strategy:
    type: Rolling
