---
# Single Node example

# In case you want to exclude some actions
# cluster_excluded_actions:
#   - destroy
#   - create
# you can definde vars here, or in group_vars/cluster_ocp1.yaml
cluster_type: sno
# This is also the zone in IPA!
cluster_base_domain: stormshift.coe.muc.redhat.com
cluster_name: ocp11
# Not needed for SNO, it will use the ip of the node.
# cluster_api_vip:
# cluster_ingress_vip:

control_plan_cores: 16
control_plan_ram_gb: 32
control_plans:
  - vm_network_ip_address: 10.32.105.128
    vm_network_mac_address: 0E:C0:EF:20:6F:80
