---
stormshift_owner_email: "rbohne@redhat.com"
stormshift_owner_purpose: "Bosch PoC Cluster!"
stormshift_owner_usage: "dedicated"

local_cluster_admins:
  - rbohne@redhat.com-admin

# Same color as for the labels: https://github.com/stormshift/support/labels
cluster_color: "#19122F"
cluster_color_fg: "#e8e8e8"
openshift_version: 4.17.15

stormshift_cluster_features:
  - redhat-internal-certificate
  - coe-sso
  - manage-with-acm
  - look-and-feel

cluster_type: classic
cluster_api_vip: 10.32.105.98
cluster_ingress_vip: 10.32.105.99

control_plan_cores: 8
control_plan_ram_gb: 16
control_plans:
  - vm_network_ip_address: 10.32.105.100
    vm_network_mac_address: 0E:C0:EF:20:69:64
  - vm_network_ip_address: 10.32.105.101
    vm_network_mac_address: 0E:C0:EF:20:69:65
  - vm_network_ip_address: 10.32.105.102
    vm_network_mac_address: 0E:C0:EF:20:69:66

worker_cores: 8
worker_ram_gb: 16
workers:
  - vm_network_ip_address: 10.32.105.103
    vm_network_mac_address: 0E:C0:EF:20:69:67
  - vm_network_ip_address: 10.32.105.104
    vm_network_mac_address: 0E:C0:EF:20:69:68
  - vm_network_ip_address: 10.32.105.105
    vm_network_mac_address: 0E:C0:EF:20:69:69
