---
#
# Prerequisites to run this playbook
# - KUBECONFIG is set
# - Your password-less ssh into OCP nodes
#

- name: Force shutdown all nodes
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Check if KUBECONFIG is set
      assert:
        that:
            - "lookup('env','KUBECONFIG')"

    - name: Get Kubernetes nodes
      set_fact:
        nodes: "{{ lookup('k8s', api_version='v1', kind='node') }}"
    - name: Add host to inventory
      add_host:
        hostname: "{{ item }}"
        groups:
        - Nodes
      with_list: "{{ nodes | json_query('[*].status.addresses[0].address') }}"

- name: Shutdown nodes
  hosts: Nodes
  remote_user: core
  tasks:

    - name: Prompt user
      pause:
        prompt: Please confirm you want to shutdown the OCP nodes! Press return to continue. Press Ctrl+c and then "a" to abort
  
    - name: Shutdown nodes
      shell: sudo shutdown -h 10
