---
#
# -------------------- Template VMs --------------------
#
template_vms:
  vars:
    ansible_host: "{{ inventory_hostname }}.{{ sysctx_dns_domain }}"
  hosts:
    rhel92-template:
      vm_cr_name: stormshift-template-rhel92
    rhel94-template:
      vm_cr_name: stormshift-template-rhel94


#
# -------------------- MICROSHIFT --------------------
#
cluster_ushift05:
  hosts:
    ushift05:


cluster_ushift06:
  hosts:
    ushift06:

cluster_ushift07:
  hosts:
    ushift07:

cluster_ushift08:
  hosts:
    ushift08:

cluster_ushift09:
  hosts:
    ushift09:

cluster_ushift10_eus:
  hosts:
    ushift10-eus:

cluster_ushift11_ga:
  hosts:
    ushift11-ga:

cluster_ushift12_rc:
  hosts:
    ushift12-rc:

cluster_ushift13_ec:
  hosts:
    ushift13-ec:

cluster_ushift14:
  hosts:
    ushift14:

cluster_ushift15_ostree:
  hosts:
    ushift15-ostree:

cluster_ushift16_ostree:
  hosts:
    ushift16-ostree:

cluster_ushift20:
  hosts:
    ushift20:

cluster_ushift21:
  hosts:
    ushift21-qe1:

cluster_ushift22:
  hosts:
    ushift22:

cluster_ushift_edge_fleet:
  vars:
    stormshift_owner_email: "dfroehli@redhat.com"
    stormshift_owner_purpose: "Edge Fleet Demo"
    vm_cores: 2
    vm_memory: "4Gi"
    # install_type - one of: rpm, ostree, imageMode
    ushift_install_type: ostree
    ushift_uefi_boot_file: "http://ushift-imgbld.stormshift.coe.muc.redhat.com/edge-network-install/EFI/BOOT/BOOTX64.EFI"
    ansible_host: "{{ inventory_hostname }}.{{ sysctx_dns_domain }}"
    ansible_ssh_pass: redhat02 

  hosts:
    ushift-edgefleet-30:
      network_ip_address: 10.32.99.30
      network_mac_address: 0E:C0:EF:20:63:1E
    ushift-edgefleet-31:
      network_ip_address: 10.32.99.31
      network_mac_address: 0E:C0:EF:20:63:1F
    ushift-edgefleet-32:
      network_ip_address: 10.32.99.32
      network_mac_address: 0E:C0:EF:20:63:20
    ushift-edgefleet-33:
      network_ip_address: 10.32.99.33
      network_mac_address: 0E:C0:EF:20:63:21
    ushift-edgefleet-34:
      network_ip_address: 10.32.99.34
      network_mac_address: 0E:C0:EF:20:63:22
    ushift-edgefleet-35:
      network_ip_address: 10.32.99.35
      network_mac_address: 0E:C0:EF:20:63:23
    ushift-edgefleet-36:
      network_ip_address: 10.32.99.36
      network_mac_address: 0E:C0:EF:20:63:24
    ushift-edgefleet-37:
      network_ip_address: 10.32.99.37
      network_mac_address: 0E:C0:EF:20:63:25
    ushift-edgefleet-38:
      network_ip_address: 10.32.99.38
      network_mac_address: 0E:C0:EF:20:63:26
    ushift-edgefleet-39:
      network_ip_address: 10.32.99.39
      network_mac_address: 0E:C0:EF:20:63:27

# Single Node example

cluster_ocp11:
  vars:
    # you can definde vars here, or in group_vars/cluster_ocp1.yaml
    cluster_type: sno
    # This is also the zone in IPA!
    cluster_base_domain: stormshift.coe.muc.redhat.com
    cluster_name: ocp11
    # Not needed for SNO, it will use the ip of the node.
    # cluster_api_vip:
    # cluster_ingress_vip:

  children:
    cluster_ocp11_workers:
      hosts:
    cluster_ocp11_cp:
      hosts:
        ocp11-control-1:
          # you can definde vars here, or in host_vars/ocp11-control-1.yaml
          vm_network_ip_address: 10.32.105.128
          vm_network_mac_address: 0E:C0:EF:20:6F:80
          vm_cores: 16
          vm_memory_gb: 32

# Multi Node example
cluster_ocp1:
  vars:
    # you can definde vars here, or in group_vars/cluster_ocp1.yaml

    # cluster_base_domain is also the zone in IPA!
    cluster_base_domain: stormshift.coe.muc.redhat.com
    cluster_type: classic
    cluster_name: ocp1
    cluster_api_vip: 10.32.105.64
    cluster_ingress_vip: 10.32.105.65

  children:
    cluster_ocp1_workers:
      vars:
        vm_cores: 8
        vm_memory_gb: 16
      hosts:
        ocp1-worker-1:
          vm_network_ip_address: 10.32.105.66
          vm_network_mac_address: 0E:C0:EF:20:69:42
        ocp1-worker-2:
          vm_network_ip_address: 10.32.105.67
          vm_network_mac_address: 0E:C0:EF:20:69:43
        ocp1-worker-3:
          vm_network_ip_address: 10.32.105.68
          vm_network_mac_address: 0E:C0:EF:20:69:44
    cluster_ocp1_cp:
      vars:
        vm_cores: 16
        vm_memory_gb: 32
      hosts:
        ocp1-control-1:
          # you can definde vars here, or in host_vars/ocp1-control-1.yaml
          vm_network_ip_address: 10.32.105.69
          vm_network_mac_address: 0E:C0:EF:20:69:45
        ocp1-control-2:
          vm_network_ip_address: 10.32.105.70
          vm_network_mac_address: 0E:C0:EF:20:69:46
        ocp1-control-3:
          vm_network_ip_address: 10.32.105.71
          vm_network_mac_address: 0E:C0:EF:20:69:47
