# Replace the default nodejs image with a special one
# that uses red hat internal nexus as npm proxy (see npmrc)
# Reason: https://docs.google.com/document/d/1dn1gQFaJ_Q0IOeRAnFAsBMgVRnwA8ieLQV-AG56hOGU/edit#
---
- name: Replace default nodejs image with npm red hat nexus proxy config
  gather_facts: false
  hosts: localhost
  vars:
    NAMESPACE: "dfroehli-nodejs-rh"

  tasks:
  - name: Create OpenShift Project
    tags: prj
    k8s:
      state: present
      wait: true
      definition:
        kind: Project
        apiVersion: project.openshift.io/v1
        metadata:
          name: "{{NAMESPACE}}"
          annotations:
            openshift.io/description: "NodeJS S2I Image with RH npm proxy"
            openshift.io/display-name: ""

  - name: Create Image Stream for NodeJS Baseimage
    tags: is
    k8s:
      state: present
      wait: true
      definition:
        apiVersion: image.openshift.io/v1
        kind: ImageStream
        metadata:
          name: nodejs-10-rhel7
          namespace: "{{NAMESPACE}}"
        spec:
          lookupPolicy:
            local: false
          tags:
            - annotations:
                openshift.io/imported-from: registry.access.redhat.com/rhscl/nodejs-10-rhel7
              from:
                kind: DockerImage
                name: registry.access.redhat.com/rhscl/nodejs-10-rhel7
              generation: 2
              importPolicy:
                scheduled: true
              name: latest
              referencePolicy:
                type: Source
  - name: Rolebind for openshift images
    tags: rb
    k8s:
      state: present
      definition:
        apiVersion: authorization.openshift.io/v1
        groupNames:
        - system:serviceaccounts:{{NAMESPACE}}
        kind: RoleBinding
        metadata:
          name: system:image-builder
          namespace: openshift
        roleRef:
          name: system:image-builder
        subjects:
        - kind: SystemGroup
          name: system:serviceaccounts:{{NAMESPACE}}
        userNames: null


  - name: Buildconfig
    tags: is
    k8s:
      state: present
      wait: true
      definition:
        apiVersion: build.openshift.io/v1
        kind: BuildConfig
        metadata:
          name: nodejs-rh-latest
          namespace: "{{NAMESPACE}}"
        spec:
          failedBuildsHistoryLimit: 5
          nodeSelector: null
          output:
            to:
              kind: ImageStreamTag
              name: 'nodejs:latest'
              namespace: openshift
          postCommit: {}
          resources: {}
          runPolicy: Serial
          source:
            contextDir: 410_nodeImageWithRHNexus
            git:
              uri: 'https://github.com/DanielFroehlich/stormshift.git'
            type: Git
          strategy:
            dockerStrategy:
              from:
                kind: ImageStreamTag
                name: 'nodejs-10-rhel7:latest'
            type: Docker
          successfulBuildsHistoryLimit: 5
          triggers:
            - github:
                secret: 6ZuT7zBYmsMbtMFLrOO3
              type: GitHub
            - generic:
                secret: EOQUBK9hO6BWdHsXZgPi
              type: Generic
            - type: ConfigChange
            - imageChange:
              type: ImageChange

  - name: Buildconfig
    tags: is
    k8s:
      state: present
      wait: true
      definition:
        apiVersion: build.openshift.io/v1
        kind: BuildConfig
        metadata:
          name: nodejs-rh-10
          namespace: "{{NAMESPACE}}"
        spec:
          failedBuildsHistoryLimit: 5
          nodeSelector: null
          output:
            to:
              kind: ImageStreamTag
              name: 'nodejs:10'
              namespace: openshift
          postCommit: {}
          resources: {}
          runPolicy: Serial
          source:
            contextDir: 410_nodeImageWithRHNexus
            git:
              uri: 'https://github.com/DanielFroehlich/stormshift.git'
            type: Git
          strategy:
            dockerStrategy:
              from:
                kind: ImageStreamTag
                name: 'nodejs-10-rhel7:latest'
            type: Docker
          successfulBuildsHistoryLimit: 5
          triggers:
            - github:
                secret: 6ZuT7zBYmsMbtMFLrOO3
              type: GitHub
            - generic:
                secret: EOQUBK9hO6BWdHsXZgPi
              type: Generic
            - type: ConfigChange
            - imageChange:
              type: ImageChange
