---

- name: Configure DHCP
  ansible.builtin.include_tasks: 110-create-dhcp.yml
  tags: dhcp

- name: Configure DNS
  ansible.builtin.include_tasks: 120-create-dns.yml
  tags: dns

- name: Create VM
  ansible.builtin.include_tasks: 130-create-vm.yml
  tags: vm

- name: Preinstall MicroShift
  ansible.builtin.include_tasks: 150-ushift-preinstall-rpm.yml
  tags: pre

- name: Install MicroShift
  ansible.builtin.include_tasks: 160-ushift-install-rpm.yml
  tags: install

- name: Postinstall MicroShift
  ansible.builtin.include_tasks: 170-ushift-postinstall-rpm.yml
  tags: post
