# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
    - name: Set hostname
      tags: prep,hostname
      hostname:
        name: "{{inventory_hostname}}.{{ sysctx_dns_domain }}"

    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      tags: prep,swap
      changed_when: false
      shell: |
        swapoff -a

    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      tags: prep,swap
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s.*)$'
        replace: '#\1'

#
# RHEL 92 todo:  work around
# Devices file sys_serial 213e7b6b-8441-44d0-ae26-3df55bab3844 PVID MDHwM81ex62inauoWm3U415rXNZCQigI last seen on /dev/sda2 not found.
# by:
#While awaiting a fix this can be bypassed by setting use_devicesfile=0 inside of /etc/lvm/lvm.conf

    - name: Workaround Devices files not found by changing LVM Configure
      tags: prep,lvmcfg
      replace:
        path: /etc/lvm/lvm.conf
        regexp: '# use_devicesfile = 1'
        replace: 'use_devicesfile = 0'

    - name: Enable Repos
      tags: prep,repos, slow
      when: ushift_repo_list is defined
      rhsm_repository:
        state: enabled
        name: "{{ushift_repo_list}}"

    - name: Prepare for candidate Repos
#      when: dev_preview_version is defined
      tags: prep,repos
      template:
        trim_blocks: false
        src: templates/microshift-candidate.repo
        dest: /etc/yum.repos.d/microshift-candidate.repo

    - name: Install oc client and cockpit (not needed, demo purposes only)
      tags: prep,rpm
      yum:
        name:
          - openshift-clients
          - cockpit
        state: present

    - name: Enable and start cockpit
      tags: prep,cockpit
      service:
        name: cockpit.socket
        enabled: yes
        state: started

    - name: Add typical commands to bash history
      tags: prep, bash
      blockinfile:
        path: /root/.bash_history
        create: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{inventory_hostname}}"
        block: "{{ lookup('template', 'templates/microshift-bash-history-suggestions.j2') }}"


    - name: Create crio dir
      tags: prep,crio
      file:
        path: /etc/crio
        state: directory

    - name: Provide pull secrets
      tags: prep,secrets
      copy:
        content: "{{sysctx_pull_secret}}"
        dest: /etc/crio/openshift-pull-secret
        mode: 600
        owner: root
        group: root

    - name: Create kube dir
      tags: prep,cfg
      file:
        path: /root/.kube
        state: directory
        owner: root
        group: root

    - name: Create ushift dir
      tags: prep,cfg
      file:
        path: /etc/microshift
        state: directory
        owner: root
        group: root

    - name: Create LVM thin pool
      tags: prep,cfg
      lvol:
        vg: rhel
        lv: thin
        size: 16G
        opts: --thin

    - name: Provide MicroShift config file
      tags: prep,cfg
      template:
        src: templates/microshift-config.yaml.j2
        dest: /etc/microshift/config.yaml

    - name: Provide lvmd config file
      tags: prep,cfg
      template:
        src: templates/microshift-lvmd.yaml.j2
        dest: /etc/microshift/lvmd.yaml


    - name: Firewall add cluster network to trusted zone
      tags: prep, firewall
      firewalld:
        immediate: yes
        permanent: yes
        zone: trusted
        source: 10.42.0.0/16
        state: enabled

    - name: Firewall add DNS to trusted zone
      tags: prep, firewall
      firewalld:
        immediate: yes
        permanent: yes
        zone: trusted
        source: 169.254.169.1
        state: enabled

    - name: Firewall open API port for external access
      tags: prep, firewall
      firewalld:
        immediate: yes
        permanent: yes
        port: 6443/tcp
        state: enabled

    - name: Firewall open cockpit port for external access
      tags: prep, firewall
      firewalld:
        immediate: yes
        permanent: yes
        port: 9090/tcp
        state: enabled

    - name: Install MicroShift
      when: ushift_actually_install
      tags: install, slow
      yum:
        name: 'microshift'
        state: present
      register: install

    - name: Enable and start MicroShift
      when: ushift_actually_install
      tags: install, slow
      service:
        name: microshift
        enabled: yes
        state: started

    - name: Copy kubeconfig to root user on VM
      when: ushift_actually_install
      tags: post, kubecfg
      copy:
        src: /var/lib/microshift/resources/kubeadmin/{{inventory_hostname}}.{{ sysctx_dns_domain }}/kubeconfig
        remote_src: true
        dest: /root/.kube/config
        mode: 600

    - name: Create temporary local kubeconfig file
      when: ushift_actually_install
      tags: post, kubecfg
      local_action:
        module: ansible.builtin.tempfile
        state: file
        suffix: temp
      register: temp_kubeconfig

    - name: Fetch kubeconfig from remote
      when: ushift_actually_install
      tags: post, kubecfg
      fetch:
        src: /root/.kube/config
        dest: "{{temp_kubeconfig.path}}"
        flat: true

    - name: Deploy VolumeSnapshotClass
      tags: post,vsc
      when: ushift_actually_install
      local_action:
        module: kubernetes.core.k8s
        kubeconfig: "{{temp_kubeconfig.path}}"
        validate_certs: false
        state: present
        definition: "{{ lookup('template', 'templates/microshift-volumeSnapShotClass.yaml') }}"

    - name: Prepare VolumeSnapshotClass
      tags: post,vsc
      template:
        src: templates/microshift-volumeSnapShotClass.yaml
        dest: /root/volumeSnapshotClass.yaml

    - name: Deploy sample workload
      tags: post,sample
      when: ushift_actually_install and ushift_deploy_sample_workload
      local_action:
        module: kubernetes.core.k8s
        kubeconfig: "{{temp_kubeconfig.path}}"
        validate_certs: false
        state: present
        definition: "{{ lookup('template', 'templates/microshift-sample-app.yaml') }}"

    - name: Prepare demos
      tags: post,sample
      template:
        src: templates/{{item}}
        dest: /root/{{item}}
      loop:
        - microshift-sample-app.yaml
        - microshift-olm-demo.yaml
        - microshift-gitops-demo.yaml
        - microshift-sample-volumeSnapshot.yaml

    - name: Remove temporary local kubeconfig file
      when: temp_kubeconfig.path is defined
      tags: post, kubecfg
      ansible.builtin.file:
        path: "{{ temp_kubeconfig.path }}"
        state: absent
