---

- name: Remove MicroShift VM
  tags: vm
  local_action:
    module: kubevirt.core.kubevirt_vm
    api_key:         "{{ hostvars['isar']['k8s_auth_api_key'] }}"
    host:            "{{ hostvars['isar']['k8s_auth_host'] }}"
    validate_certs:  "{{ hostvars['isar']['k8s_auth_verify_ssl'] }}"
    state: absent
    wait: true
    name: "{{ inventory_hostname }}"
    namespace: "{{ ushift_virt_namespace }}"
