---

  - name: Remove DHCP
    tags: dhcp
    delegate_to: "{{ sysctx_network_dhcp }}"
    blockinfile:
      path: /etc/dhcp/dhcpd-dfroehli-edge.conf
      marker: "# {mark} ANSIBLE MANAGED {{inventory_hostname}}"
      state: absent
      block: |
        host {{inventory_hostname}} {
          hardware ethernet {{ network_mac_address }};
          fixed-address {{ network_ip_address }};
          option host-name "{{inventory_hostname}}";
          option domain-name "{{ sysctx_dns_domain }}";
          ddns-hostname "{{ inventory_hostname }}.{{ sysctx_dns_domain }}";
        }
    register: dhcp

  - name: Restart DHCP
    tags: dhcp
    delegate_to: "{{ sysctx_network_dhcp }}"
    service:
      name: dhcpd
      enabled: yes
      state: restarted
    when: dhcp is changed
