---

- name: Get child cluster access
  community.hashi_vault.vault_kv2_get:
    url: "{{ lookup('ansible.builtin.env', 'RH_VAULT_URL' ) }}"
    auth_method: approle
    role_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_ROLE_ID' ) }}"
    secret_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_SECRET_ID' ) }}"
    ca_cert: "{{ lookup('ansible.builtin.env', 'RH_VAULT_CA_CERT_FILENAME' ) }}"
    engine_mount_point: apps

    path: "coe-lab/cluster-credential/stormshift-{{ inventory_hostname }}"
  register: cluster_credential

- name: Temp folder
  ansible.builtin.tempfile:
    state: "directory"
  register: temp
  changed_when: False

- name: Set cluster_access_kubeconfig
  ansible.builtin.set_fact:
    cluster_access_kubeconfig: "{{ temp.path }}/kubeconfig"

- name: Write kubeconfig
  ansible.builtin.copy:
    dest: "{{ cluster_access_kubeconfig }}"
    content: "{{ cluster_credential.secret.kubeconfig }}"
  changed_when: False
