---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stormshift-automation
  namespace: stormshift-vm-templates
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: automation
  namespace: stormshift
---
apiVersion: v1
kind: Secret
metadata:
  name: automation-token
  annotations:
    kubernetes.io/service-account.name: automation
type: kubernetes.io/service-account-token