---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stormshift-automation
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - create
  - list
  - delete
  - patch
  - get
- apiGroups:
  - project.openshift.io
  resources:
  - projects
  verbs:
  - create
  - list
  - patch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hcp-automation
  namespace: stormshift
rules:
- apiGroups:
  - "hypershift.openshift.io"
  resources:
  - hostedclusters
  - nodepools
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stormshift-automation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stormshift-automation
subjects:
- kind: ServiceAccount
  name: automation
  namespace: stormshift
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stormshift-automation-self-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: self-provisioner
subjects:
- kind: ServiceAccount
  name: automation
  namespace: stormshift
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stormshift-automation-managedclusterset-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:managedclusterset:admin:stormshift
subjects:
- kind: ServiceAccount
  name: automation
  namespace: stormshift
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stormshift-automation-hcp-admin
  namespace: stormshift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hcp-automation
subjects:
- kind: ServiceAccount
  name: automation
  namespace: stormshift
