# Make stormshift namespaces visiable to all authenticated users:
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: make-all-athenticated-project-admin
  namespace: stormshift-vm-templates
subjects:
# All authenticated users:
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: stormshift-automation
    namespace: stormshift-vm-templates
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: make-all-athenticated-project-admin
  namespace: stormshift-microshift
subjects:
# All authenticated users:
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: make-all-athenticated-project-admin
  namespace: stormshift-openshift
subjects:
# All authenticated users:
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stormshift-admins-admin
  namespace: stormshift
subjects:
  - kind: Group
    name: stormshift-admins
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: automation
    namespace: stormshift
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

