apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: stormshift-template-rhel92
  name: stormshift-template-rhel92
  namespace: stormshift-vm-templates
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: stormshift-template-rhel92
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 2
        memory:
          guest: 4Gi
        resources:
          requests:
            memory: 4Gi
        machine:
          type: q35
        devices:
          disks:
          - disk:
              bus: virtio
            name: root-disk
          interfaces:
            - bridge: {}
              macAddress: '0E:C0:EF:20:69:26'
              model: virtio
              name: net-0
        clock:
          timezone: Etc/GMT
      networks:
        - multus:
            networkName: stormshift-vm-templates/coe-bridge
          name: net-0
      volumes:
      - name: root-disk
        persistentVolumeClaim:
          claimName: stormshift-template-rhel92-root
