apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
  name: coe-ssh-key
  namespace: stormshift
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: coe-lab/ssh-key/coe-muc-rsa
      metadataPolicy: None
      property: key
    secretKey: id_rsa
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: coe-lab/ssh-key/coe-muc-rsa
      metadataPolicy: None
      property: pub
    secretKey: id_rsa.pub
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: redhat-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: coe-ssh-key
