---
- name: Get certificate from Vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ lookup('ansible.builtin.env', 'RH_VAULT_URL' ) }}"
    auth_method: approle
    role_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_ROLE_ID' ) }}"
    secret_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_SECRET_ID' ) }}"
    ca_cert: "{{ lookup('ansible.builtin.env', 'RH_VAULT_CA_CERT_FILENAME' ) }}"
    engine_mount_point: apps

    path: "coe-lab/certificate/{{ common_name }}"
  register: certificate
  ignore_errors: true

- name: Certificate does not exist or is to old request on
  ansible.builtin.include_tasks: request-cert.yaml
  when: certificate.failed or (( (certificate.secret.not_after_epoch|int) - (now().strftime('%s')|int) ) < renew_in_seconds)

- name: Include optional E-Mail sent
  ansible.builtin.include_tasks: sent-email.yaml
  when: sent_email