---
# defaults file for cluster

artifacts_dir: "{{ playbook_dir }}"
openshift_install_dir: "{{ artifacts_dir }}/{{ cluster_name }}"
openshift_version: 4.15.10
openshift_install_dest: "{{ artifacts_dir }}/{{ openshift_version }}"
# openshift_install_command: "{{ artifacts_dir }}/{{ openshift_version }}/openshift-install"

openshift_mirror: "https://mirror.openshift.com"
openshift_location: "{{ openshift_mirror }}/pub/openshift-v4/clients/ocp/{{ openshift_version }}"

openshift_install_command: "{{ openshift_install_dest }}/openshift-install"


network: 10.32.96.0
network_ip_address_prefix_length: 20

network_default_gw: 10.32.111.254
network_dns_servers:
  - 10.32.96.1
  - 10.32.96.31

upload_host: https://cdi-uploadproxy-openshift-cnv.apps.isar.coe.muc.redhat.com


vm_storageclass: coe-netapp-san
vm_rootdisk_gb: 120

target_namespace: "stormshift-{{ cluster_name }}-infra"