---
# defaults file for cluster

artifacts_dir: "{{ playbook_dir }}"
openshift_install_dir: "{{ artifacts_dir }}/{{ stormshift_cluster_name }}"
openshift_version: 4.15.10
openshift_install_dest: "{{ artifacts_dir }}/{{ openshift_version }}"
# openshift_install_command: "{{ artifacts_dir }}/{{ openshift_version }}/openshift-install"

openshift_mirror: "https://mirror.openshift.com"
openshift_location: "{{ openshift_mirror }}/pub/openshift-v4/clients/ocp/{{ openshift_version }}"

openshift_install_command: "{{ openshift_install_dest }}/openshift-install"


network: 10.32.96.0
network_ip_address_prefix_length: 20

network_default_gw: 10.32.111.254
network_dns_servers:
  - 10.32.96.1
  - 10.32.96.31
