---
- name: Get child cluster access
  community.hashi_vault.vault_kv2_get:
    url: "{{ lookup('ansible.builtin.env', 'RH_VAULT_URL' ) }}"
    auth_method: approle
    role_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_ROLE_ID' ) }}"
    secret_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_SECRET_ID' ) }}"
    ca_cert: "{{ lookup('ansible.builtin.env', 'RH_VAULT_CA_CERT_FILENAME' ) }}"
    engine_mount_point: apps

    path: "coe-lab/cluster-credential/stormshift-{{ inventory_hostname }}"
  register: cluster_credential 

- name: Temp folder
  ansible.builtin.tempfile:
    state: "directory"
  register: temp

- name: Write kubeconfig
  ansible.builtin.copy:
    dest: "{{ temp.path }}/kubeconfig"
    content: "{{ cluster_credential.secret.kubeconfig }}"


- name: Fetch cluster information - oauth url
  kubernetes.core.k8s_info:
    kubeconfig: "{{ temp.path }}/kubeconfig"

    api_version: "config.openshift.io/v1"
    kind: "Ingress"
    name: "cluster"
  register: ff

- name: Cleanup oauth url
  ansible.builtin.set_fact:
    oauth_hostname: "{{ ff.resources | first | community.general.json_query(oauth_url_query) | first }}"
    client_secret: "{{ ff | ansible.builtin.to_uuid }}"
  vars:
    oauth_url_query: "status.componentRoutes[?name=='oauth-openshift'].defaultHostname"

- name: Check oauth_hostname
  ansible.builtin.fail:
    msg: "Can not findout oauth url"
  when: oauth_hostname | length == 0
