---
- name: Destroy clientSecret k8s secret
  kubernetes.core.k8s:
    api_key:         "{{ hostvars['isar']['k8s_auth_api_key'] }}"
    host:            "{{ hostvars['isar']['k8s_auth_host'] }}"
    validate_certs:  "{{ hostvars['isar']['k8s_auth_verify_ssl'] }}"

    state: absent
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ cluster_hcp_name }}-openid-client-secret-coe-sso"
        namespace: "{{ cluster_hcp_namespace }}"

- name: Remove Red Hat Root CA
  kubernetes.core.k8s:
    api_key:         "{{ hostvars['isar']['k8s_auth_api_key'] }}"
    host:            "{{ hostvars['isar']['k8s_auth_host'] }}"
    validate_certs:  "{{ hostvars['isar']['k8s_auth_verify_ssl'] }}"

    state: absent
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ cluster_hcp_name }}-redhat-current-it-root-cas-for-sso"
        namespace: "{{ cluster_hcp_namespace }}" 

- name: Destroy clients
  with_items:
    - coe-sso
    - coe-sso-admin
  community.general.keycloak_client:

    validate_certs: false
    auth_keycloak_url: https://sso.coe.muc.redhat.com
    auth_realm: master
    auth_username: admin
    auth_password: "{{ sso_admin_pw }}"

    realm: "{{ item }}"
    client_id: "oauth-{{ cluster_hcp_prefix }}{{ cluster_hcp_name }}.apps.isar.coe.muc.redhat.com"
    name: "oauth-{{ cluster_hcp_prefix }}{{ cluster_hcp_name }}.apps.isar.coe.muc.redhat.com"
  
    state: absent
  delegate_to: localhost
 