apiVersion: v1
metadata:
 name: {{layer3_ocp_name}}
baseDomain: {{sysctx_dns_domain}}
controlPlane:
  architecture: amd64
  hyperthreading: Disabled
  name: control
  platform:
    ovirt:
      cpu:
        cores: {{layer3_ocp_control_cores}}
        sockets: 1
      memoryMB: {{layer3_ocp_control_memoryMB}}
      vmType: high_performance
  replicas: 3
compute:
- architecture: amd64
  hyperthreading: Disabled
  name: worker
  platform:
    ovirt:
      cpu:
        cores: {{layer3_ocp_compute_cores}}
        sockets: 1
      memoryMB: {{layer3_ocp_compute_memoryMB}}
      vmType: high_performance
  replicas: {{layer3_ocp_num_worker}}
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.32.111.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  ovirt:
    api_vip: "{{layer3_ocp_api_ip}}"
    ingress_vip: "{{layer3_ocp_ingress_ip}}"
    ovirt_cluster_id: 1bac0328-d989-11e9-b14a-00163e34b4e4
    ovirt_network_name: ovirtmgmt
    ovirt_storage_domain_id: 4665b9ab-a632-4436-817d-2de8f1c7e363
    vnicProfileID: 0000000a-000a-000a-000a-000000000398
publish: External
pullSecret: '{{lookup('file', '/root/ocp4binaries/pull-secret.txt') }}'
sshKey: '{{sysctx_admin_ssh_key}}'
{% if sysctx_certs_path is defined %}
additionalTrustBundle: |
{{lookup('file', '{{sysctx_certs_path}}/redhat-pki-ca-chain.crt') | indent(2,true) }}
{% endif %}
