---
- name: list_ocp_nodes
  hosts: Disconnect ISOs and change boot oder
  connection: local
  gather_facts: false

  vars_files:
    - cfg/secrets_stormshift.yml
    - ../cfg/stormshift.yml
    - cfg/cluster.yml

  vars:
    engine_user: admin@internal
    engine_password: '{{secret_password}}'
    engine_url: https://{{layer2_rhev_engine_fqdn}}/ovirt-engine/api
    #  wait_for_ip: true
    debug_vm_create: true

  tasks:
    - name: Obtain SSO token
      ovirt_auth:
        url: '{{ engine_url }}'
        username: '{{ engine_user }}'
        password: '{{ engine_password }}'

    - name: Create VM
      ovirt_vm:
        auth: '{{ ovirt_auth }}'
        state: present
        name: '{{ vmname }}-{{ item.key }}'
        operating_system: 'rhcos_x64'
        cluster: Default
        boot_devices: ['hd']
        cd_iso: ''
        cloud_init:
          host_name: '{{ vmname }}'
      loop: '{{ ocp_nodes | dict2items }}'

    - name: Gather information about all VMs which names start with stefan
      ovirt_vm_info:
        auth: '{{ ovirt_auth }}'
        pattern: name="{{ vmname }}*"
      register: result

    - name: Print all VMs which names start with ocp
      ansible.builtin.debug:
        msg: '{{ result.ovirt_vms }}'
