---

- name: Configure DHCP
  ansible.builtin.include_tasks: 110-create-dhcp.yml
  tags: dhcp

- name: Configure DNS
  ansible.builtin.include_tasks: 120-create-dns.yml
  tags: dns

- name: Create VM
  ansible.builtin.include_tasks: 130-create-vm.yml
  tags: vm
