---
  - name: "Remove DNS A records for {{ inventory_hostname }} -> {{ network_ip_address }}"
    tags: dns
    local_action:
      module: community.general.ipa_dnsrecord
      zone_name: "{{ sysctx_dns_domain }}"
      record_type: A
      record_name: "{{ item }}"
      record_value: "{{ network_ip_address }}"
      state: absent
      ipa_host: "{{ sysctx_network_dns }}"
      ipa_user: "{{ lookup('ansible.builtin.env', 'IPA_USER' ) }}"
      ipa_pass: "{{ lookup('ansible.builtin.env', 'IPA_PASS' ) }}"
      validate_certs: false
    with_items:
      - "{{ inventory_hostname }}"
      - "*.apps.{{ inventory_hostname }}"

  - name: Remove DNS PTR records
    tags: dns
    local_action:
      module: community.general.ipa_dnsrecord
      zone_name: "{{ sysctx_dns_domain_reverse }}"
      record_type: PTR
# reverse domain recod name needs to be reversed.
# From aa.bb.cc.dd this is dd.cc
      record_name: "{{ network_ip_address.split('.')[3]|int }}.{{ network_ip_address.split('.')[2]|int }}"
      record_value: "{{ inventory_hostname }}.{{ sysctx_dns_domain }}."
      state: absent
      ipa_host: "{{ sysctx_network_dns }}"
      ipa_user: "{{ lookup('ansible.builtin.env', 'IPA_USER' ) }}"
      ipa_pass: "{{ lookup('ansible.builtin.env', 'IPA_PASS' ) }}"
      validate_certs: false
