---
- name: Check if cluster already exists
  ignore_errors: True
  wait_for:
    host: "api.{{ inventory_hostname }}.{{ cluster_base_domain }}"
    port: 443
    timeout: 1
  register: checkExists_results

- name: Set flag
  set_fact:
    clusterAlreadyExists: True
  when: checkExists_results is not failed

- name: Fail if not exists
  fail:
    msg: "Cluster does not exists - please use action deploy first"
  when: not clusterAlreadyExists

- name: Include post-deploy-features
  ansible.builtin.include_role:
    name: "feature-{{ item }}"
    tasks_from: post-deploy.yaml
  with_items: "{{ stormshift_cluster_features | default([]) }}"
