---

# Not yet needed
# - name: "Include post-deploy-cluster-{{ cluster_type }}"
#   include_role:
#     name: cluster
#     tasks_from: "post-deploy-cluster-{{ cluster_type }}.yaml"

- name: Waiting installation to complete
  ansible.builtin.shell: |
    export PATH={{ openshift_install_dest }}:$PATH
    {{ openshift_install_command }} --dir={{ openshift_install_dir }} agent wait-for install-complete  
  register: install_status
  retries: 60
  delay: 60
  until: install_status.rc == 0

- name: Cluster informations
  ansible.builtin.debug:
    msg: "{{ install_status.stderr_lines | map('regex_replace', 'level=info msg=\"(.*)\"', '\\1') | list }}"

- name: Include post-deploy-features
  ansible.builtin.include_role:
    name: "feature-{{ item }}"
    tasks_from: post-deploy.yaml
  with_items: "{{ stormshift_cluster_features | default([]) }}"