---

# Not yet needed
# - name: "Include post-deploy-cluster-{{ cluster_type }}"
#   include_role:
#     name: cluster
#     tasks_from: "post-deploy-cluster-{{ cluster_type }}.yaml"


- name: Include post-deploy-features
  ansible.builtin.include_role:
    name: "{{ item }}"
    tasks_from: post-deploy.yaml
  with_items: "{{ stormshift_cluster_features | default([]) }}"