---

- name: Remove api/api-int dns records
  community.general.ipa_dnsrecord:
    zone_name: "{{ cluster_base_domain }}"
    record_name: "{{ item }}.{{ cluster_name }}"
    record_type: A
    record_value: "{{ cluster_api_vip | default(vm_network_ip_address) }}"
    state: absent
    ipa_host: "{{ lookup('ansible.builtin.env', 'IPA_HOST' ) }}"
    ipa_user: "{{ lookup('ansible.builtin.env', 'IPA_USER' ) }}"
    ipa_pass: "{{ lookup('ansible.builtin.env', 'IPA_PASS' ) }}"
    validate_certs: false
  with_items:
    - api
    - api-int

- name: Remove *.apps dns records
  community.general.ipa_dnsrecord:
    zone_name: "{{ cluster_base_domain }}"
    record_name: "*.apps.{{ cluster_name }}"
    record_type: A
    record_value: "{{ cluster_ingress_vip | default(vm_network_ip_address) }}"
    state: absent
    ipa_host: "{{ lookup('ansible.builtin.env', 'IPA_HOST' ) }}"
    ipa_user: "{{ lookup('ansible.builtin.env', 'IPA_USER' ) }}"
    ipa_pass: "{{ lookup('ansible.builtin.env', 'IPA_PASS' ) }}"
    validate_certs: false

# https://github.com/kubevirt/containerized-data-importer/blob/main/doc/upload.md
- name: Delete DataVolume
  # register: my_var_with_return_value
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: "{{ cluster_name }}-agent-iso"
        namespace: "{{ target_namespace }}"

# Not yet needed
# - name: "Include pre-destroy-cluster-{{ cluster_type }}"
#   include_role:
#     name: cluster
#     tasks_from: "pre-destroy-cluster-{{ cluster_type }}.yaml"

- name: Include pre-destroy-features
  ansible.builtin.include_role:
    name: "feature-{{ item }}"
    tasks_from: pre-destroy.yaml
  with_items: "{{ stormshift_cluster_features | default([]) }}"