# assumes: default kubeconfig points to hub cluster
---
# Important: namespace must be equal to clustername - each cluster must have
# its own namespace - multiple clusters in a single namespace does not work
- name: "Create Namespace >{{ acm_hub_clustername }}< in hub cluster"
  tags: acm
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ acm_hub_clustername }}"

- name: Get cluster authentfication from Vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ lookup('ansible.builtin.env', 'RH_VAULT_URL' ) }}"
    auth_method: approle
    role_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_ROLE_ID' ) }}"
    secret_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_SECRET_ID' ) }}"
    ca_cert: "{{ lookup('ansible.builtin.env', 'RH_VAULT_CA_CERT_FILENAME' ) }}"
    engine_mount_point: apps

    path: "coe-lab/cluster-credential/{{ acm_hub_clustername }}"
  register: acm_hub_cluster_credential

- name: Create auto-import-secret in hub
  tags: acm
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "auto-import-secret"
        namespace: "{{ acm_hub_clustername }}"
      stringData:
        autoImportRetry: "5"
        kubeconfig: "{{ acm_hub_cluster_credential.secret.kubeconfig }}"
        server: "{{ acm_spoke_api_endpoint }}"
      type: Opaque

- name: "Create ManagedCluster >{{ acm_hub_clustername }}< in hub"
  tags: acm
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cluster.open-cluster-management.io/v1
      kind: ManagedCluster
      metadata:
        name: "{{ acm_hub_clustername }}"
        labels:
          cloud: auto-detect
          vendor: auto-detect
          cluster.open-cluster-management.io/clusterset: "{{acm_hub_clusterset}}"
      spec:
        hubAcceptsClient: true
        managedClusterClientConfigs:
        - url: "https://{{ acm_spoke_api_endpoint }}"

- name: "Create KlusterletAddonConfig >{{ acm_hub_clustername }}< in hub"
  tags: acm
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: agent.open-cluster-management.io/v1
      kind: KlusterletAddonConfig
      metadata:
        name: "{{acm_hub_clustername}}"
        namespace: "{{ acm_hub_clustername }}"
      spec:
       clusterName: "{{acm_hub_clustername}}"
       clusterNamespace: "{{ acm_hub_clustername }}"
       applicationManager:
         enabled: true
         argocdCluster: false
       policyController:
         enabled: true
       searchCollector:
         enabled: true
       certPolicyController:
         enabled: true
       iamPolicyController:
         enabled: true
