---

- name: "Remove ManagedCluster >{{ acm_hub_clustername }}< from ACM"
  tags: acm
  kubernetes.core.k8s:
    state: absent
    wait: true
    definition:
      apiVersion: cluster.open-cluster-management.io/v1
      kind: ManagedCluster
      metadata:
        name: "{{ acm_hub_clustername }}"


- name: "Remove Namespace  >{{ acm_hub_clustername }}< from HubCluster"
  tags: acm
  kubernetes.core.k8s:
    state: absent
    wait: true
    definition:
      apiVersion: v1
      kind: Namespace
      metadgsata:
        name: "{{ acm_hub_clustername }}"
