---
- hosts: idracs
  connection: local
  name: Get Installed Firmware Inventory
  gather_facts: False
  vars_files:
    - cfg/secrets_{{sysctx_instance_name}}.yml
    - cfg/stormshift.yml

  tasks:
  - name: Configure SATA RAID
    dellemc_idrac_storage_volume:
      idrac_ip:        "{{layer0_idrac_ip}}"
      idrac_user:      "{{layer0_idrac_user}}"
      idrac_pwd:       "{{layer0_idrac_pwd}}"
      state:           "create"
      raid_reset_config:         "True"
      controller_id:   "RAID.Integrated.1-1"
      volume_type:     "RAID 5"
      number_dedicated_hot_spare:  1
      disk_cache_policy:          "Enabled"
      write_cache_policy:         "WriteBack"
      read_cache_policy:          "ReadAhead"
      media_type:                 "SSD"
      stripe_size:                 65536
      span_length:               4
      span_depth:                1
      raid_init_operation:        "Fast"
      volumes:
          - name:                   "vd_boot"
            drives:
               id:           [
                               "Disk.Bay.0:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                               "Disk.Bay.1:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                               "Disk.Bay.2:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                               "Disk.Bay.3:Enclosure.Internal.0-1:RAID.Integrated.1-1"
                             ]
            capacity:          10
          - name:              "vd_sataraid"
            drives:
               id:           [
                               "Disk.Bay.0:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                               "Disk.Bay.1:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                               "Disk.Bay.2:Enclosure.Internal.0-1:RAID.Integrated.1-1",
                               "Disk.Bay.3:Enclosure.Internal.0-1:RAID.Integrated.1-1"
                             ]
            capacity:          4459
