---
- name: "Install RHEV"
  hosts: layer1
  remote_user: root
  gather_facts: yes
  vars_files:
    - cfg/secrets_{{sysctx_instance_name}}.yml

  tasks:
# -------------------------- subscription and repo stuff ---------------------
  - name: Register with Red Hat Subscription Manager
    tags: rhsm,slow
    redhat_subscription:
      state: present
      username: "{{ sysctx_rhsm_user}}"
      password: "{{ sysctx_rhsm_pswd}}"
      pool_ids: "{{ sysctx_rhsm_poolid_phys}}"

  - name: Disable all Repos
    tags: repos,slow
    rhsm_repository:
      name: '*'
      state: disabled

# ---- RHEV 4.3
#  - name: Enable Required Repos
#    tags: repos,slow
#    rhsm_repository:
#      name:
#        - rhel-7-server-rpms
#        - rhel-7-server-ansible-2-rpms
#        - rhel-7-server-extras-rpms
#        - rhel-7-server-supplementary-rpms
#        - rhel-7-server-rhv-4.2-manager-rpms
#        - rhel-7-server-rhv-4-manager-tools-rpms
#        - rhel-7-server-rhv-4-mgmt-agent-rpms
#        - jb-eap-7-for-rhel-7-server-rpms
#      state: enabled

# ---- RHEV 4.4
  - name: Enable Required Repos
    tags: repos,slow
    rhsm_repository:
      name:
      - rhel-8-for-x86_64-baseos-rpms
      - rhel-8-for-x86_64-appstream-rpms
      - rhv-4-mgmt-agent-for-rhel-8-x86_64-rpms
      - fast-datapath-for-rhel-8-x86_64-rpms
      - ansible-2.9-for-rhel-8-x86_64-rpms
      - advanced-virt-for-rhel-8-x86_64-rpms
      state: enabled

  - name: Updating all packages to latest
    tags: update,slow
    yum:
      name: '*'
      state: latest
    register: yumupdate

  - name: Disable watchdog to avoid reboot hangups
    sysctl:
      name: kernel.nmi_watchdog
      value: "0"
      sysctl_set: yes
      reload: yes


  - name: Reboot
    tags: update,slow
    reboot:
    when: yumupdate is defined and yumupdate is changed

# -------------------------- cockpit stuff  ---------------------
  - name: Install cockpit
    tags: cockpit,slow
    yum:
      name: cockpit
      state: latest

  - name: Open Firewall for cockpit
    tags: cockpit
    firewalld:
     service: cockpit
     permanent: yes
     immediate: yes
     state: enabled

  - name: Enable cockpit service
    tags: cockpit
    service:
      name: cockpit
      enabled: yes
      state: started

  - name: Add monitoring user for cokcpit
    tags: cockpit
    user:
      name: monitor
      password: "$6$mysecretsalt$aT7pE2g.eKUxv/BAP6bmhhi/MnY1MKGUQfUn7iW5JqPGzuHbIKrK1G6d2/ATeTlHwnV4WMiI3NjofmKzLTFP6/"

  - name: Copy stormshift server cert to bastion
    tags: cockpit
    copy:
      src: "{{sysctx_certs_path}}"
      dest: "/root/certs"
    when: sysctx_certs_path is defined

  - name: Assemble cockpit certs
    tags: cockpit
    shell: "cat stormshift.crt redhat-pki-ca-chain.crt stormshift.key  >>/etc/cockpit/ws-certs.d/1-stormshift.cert"
    args:
      chdir: /root/certs/
      creates: "/etc/cockpit/ws-certs.d/1-stormshift.cert"
    register: cockpitcert
    when: sysctx_certs_path is defined

  - name: Restart cockpit service
    tags: cockpit
    service:
      name: cockpit
      state: restarted
    when: cockpitcert is changed


# ----------------------- setup bind as DNS Server
  - name: Install BIND
    tags: dns,slow
    yum:
      name: bind
      state: latest

  - name: Configure BIND to listen on em1
    lineinfile:
      regexp: ".*listen-on port 53.*"
      line: "  listen-on port 53 { 127.0.0.1; {{ layer1_host_ip_adress }}; };"
      path: /etc/named.conf
    tags:
      - dns

  - name: Configure BIND not to listen on ipv6
    lineinfile:
      line: 'OPTIONS="-4"'
      path: /etc/sysconfig/named
    tags:
      - dns

  - name: configure BIND to answer external queries
    lineinfile:
      line: "  allow-query     { any; };"
      regexp: ".*allow-query.*"
      path: /etc/named.conf
    tags:
      - dns
  - name: configure BIND to forward to coe muc dns
    lineinfile:
      line: "  forwarders {10.32.96.1;};"
      regexp: ".*forwarders.*"
      insertafter: ".*allow-query.*"
      path: /etc/named.conf
    tags:
      - dns

  - name: create a sensible serial for BIND zone
    shell: date +%Y%m%d$((`date +%-H`*4+`date +%-M`/8))
    register: bind_zone_serial
    changed_when: False
    tags:
      - dns

  - name: create zone file
    template:
      src: templates/bind.zone.j2
      dest: /etc/named/{{ sysctx_dns_domain }}.zone
    tags:
      - dns

  - name: add zone db to bind config
    lineinfile:
      line: "zone \"{{ sysctx_dns_domain }}\" { type master; file \"/etc/named/{{ sysctx_dns_domain }}.zone\"; };"
      path: /etc/named.rfc1912.zones
    tags:
      - dns

  - name: Enable dns server
    service:
      name: named
      enabled: yes
      state: restarted
    tags:
      - dns

  - name: Open Firewall for dns
    firewalld:
     service: dns
     permanent: yes
     immediate: yes
     state: enabled
    tags:
      - dns

  - name: Install hosted engine setup package
    tags: slow
    yum:
      name:
        - ovirt-hosted-engine-setup
      state: latest


# -------------------------- storage stuff  ---------------------
  - name: Create logical volumes for rhev
    tags: storage
    lvol:
      vg: sataraid
      lv: rhev-"{{item.vol}}"
      size: "{{item.size}}"
      state: present
    with_items: "{{layer2_rhev_storage_nfs_vols}}"

  - name: Create filesystems for rhev
    tags: storage
    filesystem:
      fstype: xfs
      dev: /dev/mapper/sataraid-rhev--{{item.vol}}
    with_items: "{{layer2_rhev_storage_nfs_vols}}"

  - name: Mount file systems for rhev
    tags: storage
    mount:
      path: "{{layer2_rhev_storage_nfs_path}}/{{item.vol}}"
      src: /dev/mapper/sataraid-rhev--{{item.vol}}
      fstype: xfs
      state: mounted
    with_items: "{{layer2_rhev_storage_nfs_vols}}"

# -------------------------- nfs export stuff  ---------------------
  - name: Make directory for nfs export
    tags: storage
    file:
      path: "{{layer2_rhev_storage_nfs_path}}/{{item.vol}}"
      owner: vdsm
      group: kvm
      mode: "0755"
      state: directory
    with_items: "{{layer2_rhev_storage_nfs_vols}}"

  - name: Export nfs directory
    tags: storage
    lineinfile:
      path: /etc/exports
      line: '{{layer2_rhev_storage_nfs_path}}/{{item.vol}} *(async,wdelay,rw)'
      create: yes
    with_items: "{{layer2_rhev_storage_nfs_vols}}"

  - name: Enable nfs
    service:
      name: nfs-server
      enabled: yes
      state: started
    tags:
      - storage

  - name: Open Firewall for nfs
    firewalld:
     service: nfs
     permanent: yes
     immediate: yes
     state: enabled
    tags:
      - storage

# vi /etc/sysconfig/nfs
# (Enable ports)
#LOCKD_TCPPORT=32803
#LOCKD_UDPPORT=32769
#MOUNTD_PORT=892
#RQUOTAD_PORT=875
#STATD_PORT=662
#STATD_OUTGOING_PORT=2020

#systemctl enable nfs-server

#systemctl restart nfs-config

#firewall-cmd --add-service=nfs --permanent


  - name: Prepare engine deployment
    tags: engine
    template:
      src: templates/hosted-engine-deploy-answers.txt.j2
      dest: /root/hosted-engine-deploy-answers.txt

  - name: Test for existing engine deployment
    tags: engine
    command: hosted-engine --check-liveliness
    register: he_check_result
    ignore_errors: True
    changed_when: False

  - name: Undeploy hosted engine
    tags: engine
    shell: /usr/sbin/ovirt-hosted-engine-cleanup -q
    when: he_check_result.rc!=0

  - name: Make sure storage path is empty
    tags: engine
    shell: rm -rf {{layer2_rhev_storage_nfs_path}}/{{item}}/*
#    warn: false
    with_items:
      - hostedEngine
      - data
      - export
      - iso
    when: he_check_result.rc != 0

  - name: Deploy rhev hosted engine - time for coffee!
    tags: engine
    shell: hosted-engine --deploy  --config-append=/root/hosted-engine-deploy-answers.txt
    when: he_check_result.rc != 0

  - name: Check hosted engine liveliness after deployment
    tags: engine
    command: hosted-engine --check-liveliness
    when: he_check_result.rc != 0

- name: "Deploy Insights"
  hosts: layer1
  remote_user: root
  gather_facts: yes
  vars_files:
    - cfg/secrets_{{sysctx_instance_name}}.yml
  roles:
    - { role: redhatinsights.insights-client, when: ansible_os_family == 'RedHat' }

# TODO: If previous command did install something, reboot to be sure we are up to date:
#  - name: reboot machine
#    reboot:
#      msg: "Rebooting now for updates to take effect"

# Deploy hosted engine:
#
#hosted-engine --deploy  --config-append=hosted-engine-deploy-answers.txt
#hosted-engine --check-liveliness
#hosted-engine --check-deployed

# Destroy:
#/usr/sbin/ovirt-hosted-engine-cleanup -q
# rm -rf /var/rhev/storage

# ----------------------- setup ansible modules
#  - name: Install ansible roles
#    yum:
#      name:
#        - ovirt-ansible-roles
#      state: latest
