---
# Variables shared by all ennvironment:
# ---------------------------


# Systemcontext stuff, i.e. external components / facts:
sysctx_dns_domain: "stormshift.coe.muc.redhat.com"
sysctx_dns_domain_reverse: "32.10.in-addr.arpa"

sysctx_network_dhcp: "inf1.coe.muc.redhat.com"
sysctx_network_dns: "inf1.coe.muc.redhat.com"
sysctx_network_gateway: "10.32.111.254"
sysctx_network: "10.32.96.0"
sysctx_network_cidr: "20"

# Base layer cluster:
# Access token via credentials / env variable set:
K8S_AUTH_HOST: "https://api.isar.coe.muc.redhat.com:6443"
K8S_AUTH_VERIFY_SSL: false
# DNS server host endpoint (IPA)
# (username+pswd via credentials)
IPA_HOST: "{{sysctx_network_dns}}"


# ---------------------------
# Template VMs related common vars:
stormshift_template_vms_namespace: stormshift-vm-templates


# ---------------------------
# Microshift related common vars:
ushift_virt_namespace: stormshift-microshift
ushift_repo_ec: "https://mirror.openshift.com/pub/openshift-v4/x86_64/microshift/ocp-dev-preview"
ushift_repo_rc: "https://mirror.openshift.com/pub/openshift-v4/x86_64/microshift/ocp"
ushift_vm_storageclass: "coe-netapp-san"
# possible additional features: cockpit, manage_with_acm
ushift_additional_features: {}
ushift_use_local_quay_proxy: false

# echo -n SECRET | ansible-vault encrypt_string --vault-password-file .vault_pass
sso_admin_pw: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31316136623133643537363631303331396332663964616439363236393835653637633166393931
          3336333761326165396436366638653633323832346464310a366436303762366432383165326239
          61613464386132393937353435326462643633623361353362396239363033323136643363333537
          3363613032633664370a326635383463623931353133653665653039643762613434643465633466
          3232
