---
# Variables shared by all ennvironment:
# ---------------------------
# Systemcontext stuff, i.e. external components / facts:
sysctx_dns_domain: "stormshift.coe.muc.redhat.com"
sysctx_dns_domain_reverse: "32.10.in-addr.arpa"

sysctx_network_dhcp: "inf1.coe.muc.redhat.com"
sysctx_network_dns: "inf1.coe.muc.redhat.com"
sysctx_network_gateway: "10.32.111.254"
sysctx_network: "10.32.96.0"
sysctx_network_cidr: "20"

# ---------------------------
# Template VMs related common vars:
stormshift_template_vms_namespace: stormshift-vm-templates


# ---------------------------
# Microshift related common vars:
ushift_virt_namespace: stormshift-microshift
ushift_repo_ec: "https://mirror.openshift.com/pub/openshift-v4/x86_64/microshift/ocp-dev-preview"
ushift_repo_rc: "https://mirror.openshift.com/pub/openshift-v4/x86_64/microshift/ocp"
ushift_vm_storageclass: "coe-netapp-san"
# possible additional features: cockpit, manage_with_acm
ushift_additional_features: {}
