stormshift_owner_email: "dfroehli@redhat.com"
stormshift_owner_purpose: "Used for bootc image building"
ushift_version: 4.18
ushift_preview_version: latest-4.18
ushift_preview_version_dep_ec: 4.19-el9-beta
ushift_preview_version_dep_rc: 4.18-el9-beta
# repo, one of: EC/RC/standard
ushift_repo: standard
ushift_actually_install: false
ushift_deploy_sample_workload: false
ushift_use_local_quay_proxy: false
vm_cores: 4
vm_memory: "8Gi"
vm_template: "rhel94"
network_ip_address: 10.32.105.41
network_mac_address: 0E:C0:EF:20:69:29
ushift_repo_list:
      - rhel-9-for-x86_64-appstream-eus-rpms
      - rhel-9-for-x86_64-baseos-eus-rpms

#      - gitops-1.12-for-rhel-9-x86_64-rpms
# install_type - one of: rpm, ostree, imageMode
ushift_install_type: rpm
