stormshift_owner_email: ""
stormshift_owner_purpose: ""
ushift_version: 4.17
ushift_preview_version: latest-4.18
ushift_preview_version_dep_ec: 4.19-el9-beta
ushift_preview_version_dep_rc: 4.18-el9-beta
# repo, one of: EC/RC/standard
ushift_repo: standard
ushift_actually_install: true
ushift_deploy_sample_workload: false
vm_cores: 2
vm_memory: "2Gi"
vm_template: "rhel94"
network_ip_address: 10.32.99.2
network_mac_address: 0E:C0:EF:20:63:02
ushift_repo_list:
      - rhocp-4.17-for-rhel-9-x86_64-rpms
      - fast-datapath-for-rhel-9-x86_64-rpms
# install_type - one of: rpm, ostree, imageMode
ushift_install_type: rpm
